# Generated by Django 6.0 on 2026-03-09 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='derivation_path',
            field=models.CharField(default="m/44'/0'/0'/0/0", max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_cold_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_hardware_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='m_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wallet',
            name='mnemonic_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='n_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wallet',
            name='redeem_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='seed_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('hd', 'HD Wallet'), ('multisig', 'Multi-Signature'), ('simple', 'Simple Address')], default='hd', max_length=20),
        ),
        migrations.CreateModel(
            name='ColdStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('paper', 'Paper Wallet'), ('hardware', 'Hardware Wallet'), ('airgap', 'Air-gapped Computer')], max_length=20)),
                ('location_encrypted', models.TextField(blank=True, null=True)),
                ('access_controls', models.JSONField(blank=True, default=dict)),
                ('last_audit', models.DateTimeField(blank=True, null=True)),
                ('next_audit', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cold_storage', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('mnemonic', 'Mnemonic Phrase'), ('private_key', 'Private Key'), ('keystore', 'Keystore File'), ('paper', 'Paper Backup')], max_length=20)),
                ('backup_data_encrypted', models.TextField()),
                ('location_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('is_secure', models.BooleanField(default=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('address_type', models.CharField(default='p2pkh', max_length=20)),
                ('derivation_path', models.CharField(blank=True, max_length=100, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='wallet.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'is_used'], name='wallet_wall_wallet__f59455_idx')],
                'unique_together': {('wallet', 'address')},
            },
        ),
    ]
