# Generated by Django 6.0 on 2026-03-10 03:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('frozen_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_fees_paid', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('margin_used', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('margin_free', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('min_order_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('max_order_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_precision', models.IntegerField(default=8)),
                ('size_precision', models.IntegerField(default=8)),
                ('maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0010'), max_digits=6)),
                ('taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0010'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_margin_trading', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='trading_tra_symbol_dfdd86_idx'), models.Index(fields=['is_active'], name='trading_tra_is_acti_84cc5f_idx')],
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop', 'Stop Order'), ('stop_limit', 'Stop Limit'), ('iceberg', 'Iceberg Order'), ('twap', 'Time-Weighted Average Price')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('filled_size', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('time_in_force', models.CharField(choices=[('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate Or Cancel'), ('FOK', 'Fill Or Kill'), ('GTD', 'Good Till Date')], default='GTC', max_length=3)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('iceberg_display_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('client_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fee_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_orders', to=settings.AUTH_USER_MODEL)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('volume_1h', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='trading.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('taker_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('maker_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maker_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maker_trades', to='trading.order')),
                ('taker_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker_trades', to='trading.order')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingpair')),
            ],
            options={
                'indexes': [models.Index(fields=['trading_pair', 'created_at'], name='trading_tra_trading_4bacba_idx'), models.Index(fields=['taker_order'], name='trading_tra_taker_o_900d84_idx'), models.Index(fields=['maker_order'], name='trading_tra_maker_o_448bce_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.JSONField(default=list)),
                ('asks', models.JSONField(default=list)),
                ('sequence', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbook_snapshots', to='trading.tradingpair')),
            ],
            options={
                'indexes': [models.Index(fields=['trading_pair', 'sequence'], name='trading_ord_trading_7af87f_idx'), models.Index(fields=['timestamp'], name='trading_ord_timesta_4210ca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='trading_ord_user_id_d93b91_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trading_pair', 'status', 'side'], name='trading_ord_trading_7d3211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='trading_ord_status_86d666_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_order_id'], name='trading_ord_client__9d3b04_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['trading_pair', 'timestamp'], name='trading_mar_trading_82e71d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['timestamp'], name='trading_mar_timesta_e62a7c_idx'),
        ),
    ]
