# Generated by Django 6.0 on 2026-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoprice',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='high_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='low_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='price_change_percentage_24h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='volume_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='cryptoprice',
            index=models.Index(fields=['symbol', 'last_updated'], name='transaction_symbol_2bb1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoprice',
            index=models.Index(fields=['last_updated'], name='transaction_last_up_1b00b1_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoprice',
            index=models.Index(fields=['market_cap_rank'], name='transaction_market__7f56fa_idx'),
        ),
    ]
