# Generated by Django 6.0 on 2026-03-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_cryptoprice_circulating_supply_cryptoprice_high_24h_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cryptoprice',
            name='transaction_market__7f56fa_idx',
        ),
        migrations.RemoveField(
            model_name='cryptoprice',
            name='circulating_supply',
        ),
        migrations.RemoveField(
            model_name='cryptoprice',
            name='market_cap_rank',
        ),
    ]
